### ISSUE TITLE
Dear author, I would like to ask you some questions about this qt-SDK

### ISSUE THREAD

**Issue by Qingpo-o** [cedrikkaufmann/streamdeck-qt-cpp-sdk#1]
How do I create a usable stream deck plugin after porting to Qt? I am currently porting your library to my Qt project, but do not know how to generate the corresponding usable plugin for stream deck

**Comment by TheVoidwright** [comment]
You find the interface you have to implement in `StreamDeckPlugin.h`. Just derive your plugin class from the `StreamDeckPlugin` class and then connect your plugin slots and signals with the corresponding singnals and slots of the `StreamDeckProxy`. You can use the `void StreamDeckProxy::use(StreamDeckPlugin* plugin) const` method of the `StreamDeckProxy` class for this.

**Comment by Qingpo-o** [comment]
I did what you did and there were no problems with Qt's project, but how do I get him to work on the stream deck? Need to write a json file and html file generation plugin by yourself?

**Comment by TheVoidwright** [comment]
Yes this is just for the backend and the actual plugin called by the Streamdeck. You still need to implement the property inspector side for communication with your plugin manually, if you want to show settings and send data to your plugin within your streamdeck application when setting up the button.

**Comment by Qingpo-o** [comment]
Thanks for the reply, I'll give it a try

**Comment by Qingpo-o** [comment]
Dear author, if I use udp communication in my Qt project and listen for messages sent from IP address "127.0.0.1", port 3333, will udp communication work on the stream deck plugin? I now want to implement a udp communication message after receiving, according to different messages to call the setImage function to let the plug-in display different ICONS. But now I failed, is the plugin does not support udp communication?
